version: '3.8'

services:
  backend:
    image: mahmoudyahia/backend-image:latest
    ports:
      - "30036:2023"  # Expose container port 2023 to host
    networks:
      - my_shared_network  
    extra_hosts:
      - "host.docker.internal:172.17.0.1"  
    environment:
      - NODE_ENV=production
      - ACCESSTOKEN_SECRET_KEY=Yahia-Samir2
      - RESETTOKEN_SECRET_KEY=Yahia-Samir
      - ACCESS_TOKEN_EXPIRESIN=240
      - PORT=2023
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=BnYahia162
      - DATABASE_NAME=thelinedb
      - SSL=FALSE
      - ReCAPTCHA_SECRET_KEY=6Lf0UH0pAAAAAESMKpCDmXkKk_Hc3N7syCgotGN5
      - CLIENT_SECRET_GOOGLE=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
      - CLIENT_ID_GOOGLE=747286868244-5769tksecnl0s5jds76cdtj13phph6l7.apps.googleusercontent.com
      - PAYMENT_FATOORAH_DEV_API_KEY=rLtt6JWvbUHDDhsZnfpAhpYk4dxYDQkbcPTyGaKp2TYqQgG7FGZ5Th_WD53Oq8Ebz6A53njUoo1w3pjU1D4vs_ZMqFiz_j0urb_BH9Oq9VZoKFoJEDAbRZepGcQanImyYrry7Kt6MnMdgfG5jn4HngWoRdKduNNyP4kzcp3mRv7x00ahkm9LAK7ZRieg7k1PDAnBIOG3EyVSJ5kK4WLMvYr7sCwHbHcu4A5WwelxYK0GMJy37bNAarSJDFQsJ2ZvJjvMDmfWwDVFEVe_5tOomfVNt6bOg9mexbGjMrnHBnKnZR1vQbBtQieDlQepzTZMuQrSuKn-t5XZM7V6fCW7oP-uXGX-sMOajeX65JOf6XVpk29DP6ro8WTAflCDANC193yof8-f5_EYY-3hXhJj7RBXmizDpneEQDSaSz5sFk0sV5qPcARJ9zGG73vuGFyenjPPmtDtXtpx35A-BVcOSBYVIWe9kndG3nclfefjKEuZ3m4jL9Gg1h2JBvmXSMYiZtp9MR5I6pvbvylU_PP5xJFSjVTIz7IQSjcVGO41npnwIxRXNRxFOdIUHn0tjQ-7LwvEcTXyPsHXcMD8WtgBh-wxR8aKX7WPSsT1O8d8reb2aR7K3rkV3K82K_0OgawImEpwSvp9MNKynEAJQS6ZHe_J_l77652xwPNxMRTMASk1ZsJL
      - PAYMENT_FATOORAH_PROD_API_KEY=8JFLVztZCvghXW-mWrWaFUSgE_ZqsXRNFrutkAAHyypxDAX-B9PURPcrmitHrh2Rl_RakG2hnYX3SMkOBxOQdv9p8QzUq9I5YjsggQPRTTCJkYfkCbyWnAJESIRYGaqtSzx0MuNFDaoMp5fEQevBB3kptrsAVPIGapcQ9oBKL9OrcZc44AE-mtLj4cIGZPJ3LK_ApRtewkY-P1LXOJFYdmP5vumWCIiUVK0RZuX-gRqWxZWkfaEKotLNfHTOAbrEUBcfEng9c7A_4zy-gfluDWJnvJl9m1Ae5gNYUySJhiwy57xKg35NKfwBxZUorpuBvNyLJnXhKBo8ucjd7up7WLD3ngloT1BFFBpU3PMQxcOuZC4fG5Z5Y3ZDtZpmxhIhTPzb3cHaiYRiBxcl5thsott8LULjOw-pPZ8Kvn531Rag8hSa2eQCMP8Ac2E0vM9bphXZo04CgbJwPV-mZOtTcJ_yRuML83L4qCVHOjwS-AHDsBzl33G43WbeJ6RqQezLoCMV1zf8QIdXfGFB24236zF5CL9LG8sQ35p3uws9lE2cPuInbY-pxGJ9s1bQc_dRjvHnFEJ4O_vvRfQYeDnowlJAdZzAxDDY9H6khWVPehzZPdFQkeCJiV_RshRDVv0tlCzeYeDTlEP4tpx4U5ERFOZfj5bQZJtK9y2xbor5EI_X3_w8julSAn9JICYVUt3ZnvNjthhitWala2pu__Nnio2shpoIYmlII-eGELjrA50OXJNp
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=587
      - MAIL_USERNAME=4ea5e0dc18afea
      - MAIL_PASSWORD=56a7f0edc78341
      - MAIL_FROM=no-reply@TheLine.com
      - VERIFY_MAILER_FROM=verify@theline.social
      - VERIFY_MAILER_PASSWORD=TlS123tLs1
      - PANEL_ADDRESS=https://109.199.106.235:27648
      - SUBSCRIPTION_MAILER_FROM=sub@theline.social
      - SUBSCRIPTION_MAILER_PASSWORD=C347ee1d
      - Recovery_code=ZV8E3R96RMTNUY476TA51A7Q
      - TWILIO_AUTH_TOKEN=8921a1cf6fd1c0006f8e23ce035eb8b8
      - TWILIO_ACCOUNT_SID=AC84e36fa66b1084613920118482d47a65
      - TWILIO_PHONE_NUMBER=+15169906455
      - TWILIO_SERVICE_ID=VA1b7ef0624677e7482e8eff8e2d7b21f6
      - MSEGAT_USERSENDER=Linker
      - MSEGAT_USERNAME=Zaki_Almalki
      - MSEGAT_API_KEY=0fd2d124c543215303a13f9727aae1a3
      - B2_APPLICATION_KEY_ID=0033f6091c1d8320000000002
      - B2_APPLICATION_KEY=K003vrMz7X4Wuq24qaBrmEmUlKbn8aM
      - B2_BUCKET_ID=53afd6a0d921ec118df80312
      - B2_BUCKET_NAME=thelinesocial

  # database:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: BnYahia162
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: thelinedb
  #   ports:
  #     - "5432:5432"  # Expose PostgreSQL port
  #   networks:
  #     - my_shared_network
networks:
  my_shared_network:
    external: true
