version: '3.8'

services:
  backend:
    image: mahmoudyahia/backend-image:latest
    ports:
      - "30036:2023"  # Expose container port 2023 to host
    networks:
      - stack_comm
      - private_network
    extra_hosts:
      - "host.docker.internal:172.17.0.1"  
    environment:
      - NODE_ENV=production
      - ACCESSTOKEN_SECRET_KEY=Yahia-Samir2
      - RESETTOKEN_SECRET_KEY=Yahia-Samir
      - ACCESS_TOKEN_EXPIRESIN=240
      - PORT=2023
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - SSL=FALSE
      - ReCAPTCHA_SECRET_KEY=
      - CLIENT_SECRET_GOOGLE=
      - CLIENT_ID_GOOGLE=747286868244-5769tksecnl0s5jds76cdtj13phph6l7.apps.googleusercontent.com
      - PAYMENT_FATOORAH_DEV_API_KEY=
      - MAIL_HOST=sandbox.smtp.mailtrap.io
      - MAIL_PORT=587
      - MAIL_USERNAME=4ea5e0dc18afea
      - MAIL_PASSWORD=
      - MAIL_FROM=no-reply@TheLine.com
      - VERIFY_MAILER_FROM=verify@theline.social
      - VERIFY_MAILER_PASSWORD=
      - PANEL_ADDRESS=https://109.199.106.235:27648
      - SUBSCRIPTION_MAILER_FROM=sub@theline.social
      - SUBSCRIPTION_MAILER_PASSWORD=
      - Recovery_code=
      - TWILIO_AUTH_TOKEN=
      - TWILIO_ACCOUNT_SID=
      - TWILIO_PHONE_NUMBER=
      - TWILIO_SERVICE_ID=
      - MSEGAT_USERSENDER=Linker
      - MSEGAT_USERNAME=Zaki_Almalki
      - MSEGAT_API_KEY=
      - B2_APPLICATION_KEY_ID=
      - B2_APPLICATION_KEY=
      - B2_BUCKET_ID=
      - B2_BUCKET_NAME=


  database:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: BnYahia162
      POSTGRES_USER: postgres
      POSTGRES_DB: thelinedb
    ports:
      - "5432:5432"  # Expose PostgreSQL port
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - stack_comm
      - private_network

networks:
  private_network:
  stack_comm:
    external: true
    
volumes:
  db_data:
    driver: local
